// Curated academic subjects → the real course-code prefixes that appear across
// the 100+ colleges (codes are fragmented: MUS/MUSC/MUSIC, CIS/CS/CSCI, …). A
// subject filter matches any of its prefixes via `code ILIKE 'PREFIX%'`.
export const SUBJECTS = [
  { label: 'Accounting', prefixes: ['ACCT', 'ACCTG'] },
  { label: 'Administration of Justice', prefixes: ['ADJ', 'ADMJ', 'AJ', 'CJ', 'CRIM'] },
  { label: 'Anthropology', prefixes: ['ANTH'] },
  { label: 'Architecture', prefixes: ['ARC', 'ARCH'] },
  { label: 'Art & Art History', prefixes: ['ART', 'ARTH', 'ARTHC'] },
  { label: 'American Sign Language', prefixes: ['ASL'] },
  { label: 'Astronomy', prefixes: ['ASTR'] },
  { label: 'Automotive', prefixes: ['AUTO'] },
  { label: 'Biology', prefixes: ['BIOL', 'BIO'] },
  { label: 'Business', prefixes: ['BUS', 'BSAD', 'BA', 'MGMT'] },
  { label: 'Chemistry', prefixes: ['CHEM', 'CH'] },
  { label: 'Child Development & Early Education', prefixes: ['CD', 'CDEV', 'CHDEV', 'CHDV', 'CHLD', 'ECE'] },
  { label: 'Communication Studies', prefixes: ['COMM'] },
  { label: 'Computer Science & IT', prefixes: ['CIS', 'CS', 'CSCI', 'CSIS', 'CSS', 'COMP', 'IT'] },
  { label: 'Counseling', prefixes: ['COUN'] },
  { label: 'Culinary & Hospitality', prefixes: ['CUL', 'HOSP'] },
  { label: 'Dance', prefixes: ['DANC'] },
  { label: 'Economics', prefixes: ['ECON', 'ECONC'] },
  { label: 'Education', prefixes: ['EDUC'] },
  { label: 'Engineering', prefixes: ['ENGR'] },
  { label: 'English', prefixes: ['ENGL', 'ENGLC'] },
  { label: 'ESL / Multilingual', prefixes: ['ESL', 'ESLN', 'EMLS'] },
  { label: 'Ethnic Studies', prefixes: ['ETHN'] },
  { label: 'Film', prefixes: ['FILM'] },
  { label: 'Fire Technology', prefixes: ['FIRE'] },
  { label: 'French', prefixes: ['FREN'] },
  { label: 'Geography', prefixes: ['GEOG'] },
  { label: 'Geology', prefixes: ['GEOL'] },
  { label: 'Health', prefixes: ['HED', 'HLTH'] },
  { label: 'History', prefixes: ['HIST', 'HISTC'] },
  { label: 'Humanities', prefixes: ['HUM'] },
  { label: 'Kinesiology & PE', prefixes: ['KIN', 'KINE', 'KINS', 'KFIT', 'PE', 'PHED', 'ATHL'] },
  { label: 'Mathematics', prefixes: ['MATH', 'MATHS', 'MTH'] },
  { label: 'Music', prefixes: ['MUS', 'MUSC', 'MUSI', 'MUSIC', 'MUSP'] },
  { label: 'Nursing', prefixes: ['NURS'] },
  { label: 'Nutrition', prefixes: ['NUTR'] },
  { label: 'Philosophy', prefixes: ['PHIL'] },
  { label: 'Photography', prefixes: ['PHOT', 'PHOTO'] },
  { label: 'Physics', prefixes: ['PHYS'] },
  { label: 'Political Science', prefixes: ['POLS', 'POLSC', 'POLI'] },
  { label: 'Psychology', prefixes: ['PSYC', 'PSY', 'PSYCH', 'PSYCC'] },
  { label: 'Real Estate', prefixes: ['REAL'] },
  { label: 'Sociology', prefixes: ['SOC', 'SOCI'] },
  { label: 'Spanish', prefixes: ['SPAN'] },
  { label: 'Statistics', prefixes: ['STAT', 'STATS'] },
  { label: 'Theater', prefixes: ['THEA', 'THAR', 'THTR'] },
  { label: 'Welding', prefixes: ['WELD'] },
];

export const SUBJECT_BY_LABEL = Object.fromEntries(SUBJECTS.map((s) => [s.label, s.prefixes]));
