// CVC Exchange client (search.cvc.edu).
//
// CVC Exchange (a Quottly app) is the statewide California Community Colleges
// online course exchange. It is NOT login-blocked, renders results as plain
// server-side HTML, and covers ~115 CA community colleges — which makes it an
// excellent (a) real-data source for colleges whose own schedule we can't crack
// and (b) ground-truth cross-check for the colleges we *do* scrape.
//
// IMPORTANT — what CVC does and does not have:
//   - It lists ONLINE / async / sync-online courses only (delivery_methods=Online).
//     It is an *online exchange*, so it never shows a college's in-person sections.
//     => Treat CVC as authoritative for "what online courses exist", not for the
//        full catalog. A college can be legitimately live with 2000 in-person
//        courses and only a handful on CVC.
//   - It is keyword-driven: there is no "list everything" endpoint. To enumerate a
//     college's online catalog we sweep a broad set of subject keywords and dedupe
//     by the CVC course id.
//
// Search model (verified against the live site):
//   GET https://search.cvc.edu/search
//     filter[target_school_ids][]=<cvcId>   // restrict to courses TAUGHT by this college
//     filter[subject]=<keyword>             // required — keyword over subject/title/code
//     filter[search_type]=open_search
//     filter[search_all_universities]=true
//     commit=Find Classes
//     page=<n>                              // 10 results/page
//   Results are `.course` cards; total shown as "<N> courses".
import * as cheerio from 'cheerio';
import { fetchText } from './fetch.js';
import { geAreasFor } from './geAreas.js';

const HOST = 'https://search.cvc.edu';
const BASE = `${HOST}/search`;

// slug -> CVC university_id, for every one of our colleges that exists on CVC.
// Generated by slug-matching our colleges.json against the CVC home-institution
// dropdown (3 hand-aliased: coastline/lassen/la-trade-tech). Colleges NOT on CVC
// at all: calbright-college, north-orange-continuing-education,
// san-diego-college-of-continuing-education.
export const CVC_IDS = {
  'allan-hancock-college': 47,
  'american-river-college': 48,
  'antelope-valley-college': 49,
  'bakersfield-college': 217,
  'barstow-community-college': 218,
  'berkeley-city-college': 83,
  'butte-college': 219,
  'cabrillo-college': 84,
  'canada-college': 473,
  'cerritos-college': 480,
  'cerro-coso-community-college': 481,
  'chabot-college': 482,
  'chaffey-college': 483,
  'citrus-college': 489,
  'city-college-of-san-francisco': 490,
  'clovis-community-college': 12437,
  'coalinga-college': 12372,
  'coastline-college': 103,
  'college-of-alameda': 86,
  'college-of-marin': 593,
  'college-of-san-mateo': 697,
  'college-of-the-canyons': 474,
  'college-of-the-desert': 512,
  'college-of-the-redwoods': 673,
  'college-of-the-sequoias': 705,
  'college-of-the-siskiyous': 711,
  'columbia-college': 499,
  'compton-college': 12634,
  'contra-costa-college': 104,
  'copper-mountain-college': 4802,
  'cosumnes-river-college': 88,
  'crafton-hills-college': 504,
  'cuesta-college': 506,
  'cuyamaca-college': 507,
  'cypress-college': 508,
  'de-anza-college': 50,
  'diablo-valley-college': 89,
  'east-los-angeles-college': 55,
  'el-camino-college': 220,
  'evergreen-valley-college': 526,
  'feather-river-college': 529,
  'folsom-lake-college': 90,
  'foothill-college': 51,
  'fresno-city-college': 536,
  'fullerton-college': 539,
  'gavilan-college': 541,
  'glendale-community-college': 543,
  'golden-west-college': 91,
  'grossmont-college': 548,
  'hartnell-college': 551,
  'imperial-valley-college': 557,
  'irvine-valley-college': 563,
  'lake-tahoe-community-college': 571,
  'laney-college': 92,
  'las-positas-college': 4531,
  'lassen-college': 573,
  'lemoore-college': 12373,
  'long-beach-city-college': 579,
  'los-angeles-city-college': 56,
  'los-angeles-harbor-college': 57,
  'los-angeles-mission-college': 58,
  'los-angeles-pierce-college': 59,
  'los-angeles-southwest-college': 60,
  'los-angeles-trade-tech-college': 61,
  'los-angeles-valley-college': 62,
  'los-medanos-college': 93,
  'madera-community-college': 12641,
  'mendocino-college': 596,
  'merced-college': 599,
  'merritt-college': 94,
  'miracosta-college': 601,
  'mission-college': 603,
  'modesto-junior-college': 606,
  'monterey-peninsula-college': 607,
  'moorpark-college': 611,
  'moreno-valley-college': 5751,
  'mt-san-antonio-college': 12370,
  'mt-san-jacinto-college': 615,
  'napa-valley-college': 618,
  'norco-college': 7842,
  'ohlone-college': 642,
  'orange-coast-college': 95,
  'oxnard-college': 645,
  'palo-verde-college': 655,
  'palomar-college': 656,
  'pasadena-city-college': 658,
  'porterville-college': 666,
  'reedley-college': 567,
  'rio-hondo-college': 96,
  'riverside-city-college': 676,
  'sacramento-city-college': 97,
  'saddleback-college': 98,
  'san-bernardino-valley-college': 99,
  'san-diego-city-college': 683,
  'san-diego-mesa-college': 684,
  'san-diego-miramar-college': 685,
  'san-joaquin-delta-college': 692,
  'san-jose-city-college': 696,
  'santa-ana-college': 670,
  'santa-barbara-city-college': 100,
  'santa-monica-college': 101,
  'santa-rosa-junior-college': 701,
  'santiago-canyon-college': 4811,
  'shasta-college': 707,
  'sierra-college': 102,
  'skyline-college': 713,
  'solano-community-college': 715,
  'southwestern-college': 720,
  'taft-college': 727,
  'ventura-college': 738,
  'victor-valley-college': 740,
  'west-los-angeles-college': 63,
  'west-valley-college': 745,
  'woodland-community-college': 8023,
  'yuba-college': 757,
};

// Broad subject keyword sweep. CVC has no "list all" endpoint, so we union the
// results of many keyword searches and dedupe by CVC course id. This list covers
// the common transferable disciplines; a college's online catalog is almost
// entirely reachable through it. Order is roughly most- to least-common.
export const SUBJECTS = [
  'biology', 'chemistry', 'physics', 'mathematics', 'statistics',
  'english', 'history', 'psychology', 'sociology', 'anthropology',
  'political science', 'economics', 'business', 'accounting', 'marketing',
  'computer science', 'information technology', 'art', 'music', 'theater',
  'communication', 'philosophy', 'spanish', 'french', 'geography',
  'geology', 'astronomy', 'health', 'nursing', 'kinesiology',
  'nutrition', 'education', 'child development', 'administration of justice',
  'engineering', 'architecture', 'agriculture', 'ethnic studies',
  'humanities', 'counseling',
];

export function hasCvc(slug) {
  return Object.prototype.hasOwnProperty.call(CVC_IDS, slug);
}

function searchUrl({ cvcId, subject, page }) {
  const p = new URLSearchParams();
  p.append('filter[target_school_ids][]', String(cvcId));
  p.append('filter[subject]', subject);
  p.append('filter[search_type]', 'open_search');
  p.append('filter[search_all_universities]', 'true');
  p.append('commit', 'Find Classes');
  if (page > 1) p.append('page', String(page));
  return `${BASE}?${p.toString()}`;
}

// Parse one results page's `.course` cards into normalized course objects.
// Skips the JS-loaded "home college" grouping card (it has no real course rows).
function parsePage(html, sourceUrl) {
  const $ = cheerio.load(html);
  const courses = [];
  $('.course').each((_, el) => {
    const $c = $(el);
    const link = $c.find('a.course-details-link').first();
    const linkText = link.text().replace(/\s+/g, ' ').trim();
    if (!linkText) return; // grouping/placeholder card — no course link
    // "BIOL105 - General Biology" -> code + title
    let code = null, title = linkText;
    const m = linkText.match(/^([A-Z]{2,}[\s-]?\d[\w.\/-]*)\s*[-–—]\s*(.+)$/);
    if (m) { code = m[1].replace(/\s+/g, ''); title = m[2].trim(); }

    const college = $c.find('.course-head .font-semibold').first().text().replace(/\s+/g, ' ').trim();
    const units = ($c.find('.credit p').first().text().match(/[\d.]+/) || [null])[0];
    const term = $c.find('.term p').first().text().replace(/\s+/g, ' ').trim() || null;
    // Transferability designations (IGETC / Cal-GETC / CSU BREADTH — the GE
    // requirement areas a course satisfies).
    const transfer = $c.find('.req span').map((_, s) => $(s).text().trim()).get().filter(Boolean);
    const tuitionText = ($c.find('span.text-c_link').first().text().match(/\$[\d,.]+/) || [null])[0];
    const tuition = tuitionText ? Number(tuitionText.replace(/[^\d.]/g, '')) : null;
    // Course badges live in .tags-container; read each <li> label.
    const badges = $c.find('.tags-container .tag-container').map((_, b) => $(b).text().replace(/\s+/g, ' ').trim()).get();
    const zeroTextbookCost = badges.some((b) => /zero textbook/i.test(b));
    const qualityReviewed = badges.some((b) => /quality reviewed/i.test(b));
    // Split the "Mon DD - Mon DD" term into start/end date strings when present.
    const dm = (term || '').match(/^([A-Z][a-z]{2}\s+\d{1,2})\s*[-–]\s*([A-Z][a-z]{2}\s+\d{1,2})$/);
    const href = link.attr('href') || '';
    const cvcId = (href.match(/\/courses\/(\d+)/) || [null, null])[1];

    // Everything CVC exposes per card, kept as structured metadata so the UI and
    // Supabase can filter on transferability / tuition / badges — not buried in a
    // description string.
    const meta = {
      transferable: transfer,            // ['IGETC','Cal-GETC','CSU BREADTH']
      igetc: transfer.includes('IGETC'),
      calGetc: transfer.includes('Cal-GETC'),
      csuBreadth: transfer.some((t) => /CSU/i.test(t)),
      tuition,                            // numeric dollars
      zeroTextbookCost,
      qualityReviewed,
      startDate: dm ? dm[1] : null,
      endDate: dm ? dm[2] : null,
      cvcCourseId: cvcId,
      cvcUrl: href ? new URL(href, BASE).href : null,
      // Specific GE / A–G areas this course satisfies (from the cached area map).
      geAreas: cvcId ? geAreasFor(cvcId) : null,
    };

    courses.push({
      code,
      title,
      modality: 'online', // CVC is an online exchange; every result is online
      term,
      units,
      instructor: null, // not on the card (would need the detail page)
      section: cvcId, // CVC course id — stable per-section identifier
      description: transfer.length ? `Transfers: ${transfer.join(', ')}` : null,
      url: href ? new URL(href, BASE).href : sourceUrl,
      meta,
      _college: college,
      _transfer: transfer,
      _tuition: tuitionText,
    });
  });
  // total count is rendered as "<N> courses"
  const totalMatch = $('body').text().match(/([\d,]+)\s+courses/);
  const total = totalMatch ? Number(totalMatch[1].replace(/,/g, '')) : null;
  return { courses, total };
}

// Fetch one course's detail page (/courses/<id>) and extract everything the
// section listing exposes — EXCEPT available seats (intentionally skipped). The
// section fields each render once per section, in the same order, so we zip the
// parallel arrays by index.
export async function fetchCourseDetail(cvcCourseId) {
  const res = await fetchText(`${HOST}/courses/${cvcCourseId}`, { timeoutMs: 25000, retries: 2 });
  if (!res.ok) return null;
  const $ = cheerio.load(res.body);
  const txt = (el) => $(el).text().replace(/\s+/g, ' ').trim();

  const description = txt($('.course-description').first()) || null;
  const crn = $('.section-details-crn').map((_, e) => txt(e)).get();
  const prof = $('.section-details-professor').map((_, e) => txt(e)).get();
  const date = $('.section-details-date').map((_, e) => txt(e)).get();
  const notes = $('.section-details-notes').map((_, e) => txt(e)).get();
  // Format ("Online - Asynchronous"/"...Synchronous") renders as a button per section.
  const fmt = $('button').filter((_, e) => /Online\s*-\s*(A?synchronous)/i.test(txt(e)))
    .map((_, e) => txt(e)).get();
  const normFmt = (f) => (/asynchronous/i.test(f) ? 'Asynchronous' : /synchronous/i.test(f) ? 'Synchronous' : f || null);

  const n = Math.max(crn.length, prof.length, date.length, fmt.length);
  const sections = [];
  for (let i = 0; i < n; i++) {
    sections.push({
      crn: crn[i] || null,
      dates: date[i] || null,
      professor: prof[i] && prof[i] !== 'TBA' ? prof[i] : null,
      format: normFmt(fmt[i] || ''),
      notes: notes[i] || null,
    });
  }
  const professors = [...new Set(sections.map((s) => s.professor).filter(Boolean))];
  const formats = [...new Set(sections.map((s) => s.format).filter(Boolean))];
  // Prerequisite / recommended-prep text is embedded in the description.
  const prereq = (description && (description.match(/(Prerequisite[s]?:[^.]*\.)/i) || description.match(/(Strongly recommended:[^.]*\.)/i)) || [])[1] || null;
  return { description, sections, professors, formats, prerequisites: prereq };
}

// Run async fn over items with a small concurrency cap. Returns results in order.
async function mapLimit(items, limit, fn) {
  const out = new Array(items.length);
  let i = 0;
  async function worker() {
    while (i < items.length) {
      const idx = i++;
      try { out[idx] = await fn(items[idx], idx); } catch { out[idx] = null; }
    }
  }
  await Promise.all(Array.from({ length: Math.min(limit, items.length) }, worker));
  return out;
}

// Fetch all online courses CVC lists for one college (by slug), sweeping the
// subject keywords and deduping by CVC course id. Returns [] if the college is
// not on CVC. Never throws on a single bad fetch — it logs and continues.
//
// With { withDetails:true } it also fetches each course's detail page and merges
// section-level data (instructor, sync/async format, section dates/CRNs/notes,
// full description, prerequisites) into the course — everything but seat counts.
export async function fetchCvcCourses(slug, {
  subjects = SUBJECTS,
  maxPagesPerSubject = 25,
  onProgress = null,
  withDetails = false,
  detailConcurrency = 6,
} = {}) {
  const cvcId = CVC_IDS[slug];
  if (!cvcId) return [];

  const byId = new Map(); // cvc course id -> course (dedupe across subjects)
  for (const subject of subjects) {
    for (let page = 1; page <= maxPagesPerSubject; page++) {
      const url = searchUrl({ cvcId, subject, page });
      const res = await fetchText(url, { timeoutMs: 25000, retries: 2 });
      if (!res.ok) break; // give up this subject, move on
      const { courses } = parsePage(res.body, url);
      if (!courses.length) break; // past the last page for this subject
      for (const c of courses) {
        const key = c.section || `${c.code}|${c.title}|${c.term}`;
        if (!byId.has(key)) byId.set(key, c);
      }
      if (onProgress) onProgress({ slug, subject, page, found: byId.size });
      if (courses.length < 10) break; // last page (fewer than a full page)
    }
  }
  const list = [...byId.values()];

  // Optional deep pass: enrich each course with section-level detail.
  if (withDetails) {
    let done = 0;
    await mapLimit(list, detailConcurrency, async (c) => {
      const id = c.meta?.cvcCourseId || c.section;
      if (!id) return;
      const d = await fetchCourseDetail(id);
      if (d) {
        if (d.description) c.description = d.description; // real catalog description
        if (d.professors.length) c.instructor = d.professors.join(', ');
        c.meta = {
          ...c.meta,
          formats: d.formats,                 // ['Asynchronous'] / ['Synchronous'] / both
          professors: d.professors,
          prerequisites: d.prerequisites,
          sections: d.sections,               // [{crn,dates,professor,format,notes}] — no seats
          sectionCount: d.sections.length,
        };
      }
      done++;
      if (onProgress) onProgress({ slug, phase: 'details', found: done, total: list.length });
    });
  }
  return list;
}

// Just the headline number for a college: how many online courses CVC shows,
// using a single cheap subject probe is not enough, so this does a quick total
// via one broad query. Used by the validator for a fast "is there data?" check.
export async function cvcCourseTotal(slug, subject = 'a') {
  const cvcId = CVC_IDS[slug];
  if (!cvcId) return null;
  const res = await fetchText(searchUrl({ cvcId, subject, page: 1 }), { timeoutMs: 25000, retries: 2 });
  if (!res.ok) return null;
  return parsePage(res.body, res.url).total;
}
